# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c59eef625c9512ca53b7dc151053ea7bf9204bbe699a59b4e487f63688520c52cd2b2270b4bdbb067bc6a8311f13d48181c99467f5b938fab72ec809ca203775

test:
  secret_key_base: a76058cd7a62b11a48f30b2b941147c6eec9847a846d66c11c9348093bb536ec23d3f2a501d8ac996d7ab41fbf817f0afbf61911234fb53a453921f2205816bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
